# Generated by Django 4.2.7 on 2023-12-14 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Genre slug')),
                ('image', models.ImageField(max_length=255, upload_to=main.models.Genre.image_upload_to)),
            ],
            options={
                'verbose_name_plural': 'Genres',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subgenre_slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Subgenre slug')),
                ('image', models.ImageField(max_length=255, upload_to=main.models.SubGenre.image_upload_to)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.genre')),
            ],
            options={
                'verbose_name_plural': 'Subgenres',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('game_slug', models.SlugField(unique=True, verbose_name='Game slug')),
                ('image', models.ImageField(max_length=255, upload_to=main.models.VideoGame.image_upload_to)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('clicks', models.ManyToManyField(related_name='clicked_games', through='main.UserClick', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genre')),
                ('subgenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subgenre')),
            ],
            options={
                'verbose_name_plural': 'Video games',
                'ordering': ['-release_date'],
            },
        ),
        migrations.AddField(
            model_name='userclick',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.videogame'),
        ),
        migrations.AddField(
            model_name='userclick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
