# Generated by Django 4.2.7 on 2023-12-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='videogame',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
