# Generated by Django 4.2.7 on 2023-12-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgenre',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Series slug'),
        ),
        migrations.AddField(
            model_name='videogame',
            name='game_slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Series slug'),
        ),
    ]
