# Generated by Django 4.2.7 on 2023-12-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subgenre_slug_videogame_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgenre',
            name='slug',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Genre slug'),
        ),
        migrations.AddField(
            model_name='subgenre',
            name='subgenre_slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Subgenre slug'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='game_slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Game slug'),
        ),
    ]
