# Generated by Django 4.2.7 on 2023-12-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_subgenre_slug_genre_genre_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_slug',
            new_name='slug',
        ),
    ]
