# Generated by Django 4.2.7 on 2023-12-12 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_genre_slug_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgenre',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.genre'),
        ),
    ]
