# Generated by Django 4.2.7 on 2023-12-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subgenre_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subgenre',
            old_name='subgenre_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='videogame',
            old_name='game_slug',
            new_name='slug',
        ),
    ]
