# Generated by Django 4.2.7 on 2023-12-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_subgenre_slug_subgenre_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subgenre',
            old_name='slug',
            new_name='subgenre_slug',
        ),
        migrations.RenameField(
            model_name='videogame',
            old_name='slug',
            new_name='game_slug',
        ),
    ]
