# Generated by Django 4.2.7 on 2023-12-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_slug_subgenre_subgenre_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name_plural': 'Genre'},
        ),
        migrations.AlterModelOptions(
            name='subgenre',
            options={'verbose_name_plural': 'Subgenre'},
        ),
        migrations.AlterModelOptions(
            name='videogame',
            options={'ordering': ['-release_date'], 'verbose_name_plural': 'Video game'},
        ),
    ]
