# Generated by Django 4.2.7 on 2023-12-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_genre_options_alter_subgenre_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videogame',
            old_name='sub_genre',
            new_name='subgenre',
        ),
    ]
