# Generated by Django 4.2.7 on 2023-12-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_sub_genre_videogame_subgenre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='subgenre',
            old_name='name',
            new_name='title',
        ),
    ]
