# Generated by Django 4.2.7 on 2023-12-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_name_genre_title_rename_name_subgenre_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['title'], 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='subgenre',
            options={'ordering': ['title'], 'verbose_name_plural': 'Subgenres'},
        ),
        migrations.AlterModelOptions(
            name='videogame',
            options={'ordering': ['-release_date'], 'verbose_name_plural': 'Video games'},
        ),
    ]
