# Generated by Django 4.2.7 on 2023-12-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_description_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='regular', max_length=100),
        ),
    ]
