# Generated by Django 4.2.7 on 2023-12-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, default='', max_length=600, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('superadmin', 'superadmin')], default='user', max_length=100),
        ),
    ]
